# Generated by Django 5.0.3 on 2025-04-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0004_alter_chathistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
